repos:
- repo: https://github.com/necaris/pre-commit-pyright
  rev: 1.1.34
  hooks:
    - id: pyright
      name: pyright
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-merge-conflict
    name: check-merge-conflict
  - id: detect-private-key
    name: detect-private-key
  - id: end-of-file-fixer
    name: end-of-file-fixer
  - id: no-commit-to-branch
    name: no-commit-to-branch
  - id: trailing-whitespace
    name: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.9.3
  hooks:
  - id: isort
