version: "3.8"

services:
  app:
    build:
      context: .
    command: gunicorn booker.wsgi:application --bind 0.0.0.0:8000
    environment:
      - ALLOWED_HOSTS_FILE=/run/secrets/allowed_hosts
      - CORS_ORIGIN_WHITELIST_FILE=/run/secrets/cors_origin_whitelist
      - CSRF_TRUSTED_ORIGINS_FILE=/run/secrets/csrf_trusted_origins
      - DATABASE_URL_FILE=/run/secrets/database_url
      - SECRET_KEY_FILE=/run/secrets/secret_key
      - CODE_LENGTH=4
      - DAYS_BETWEEN=1
      - TOTAL_APARTMENTS=18
    ports:
      - "8000:8000"
    restart: always
    secrets:
      - allowed_hosts
      - cors_origin_whitelist
      - csrf_trusted_origins
      - database_url
      - secret_key
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    restart: always
    secrets:
      - postgres_password
    volumes:
      - postgres_volume:/var/lib/postgresql/data

secrets:
  allowed_hosts:
    file: ./secrets/allowed_hosts
  cors_origin_whitelist:
    file: ./secrets/cors_origin_whitelist
  csrf_trusted_origins:
    file: ./secrets/csrf_trusted_origins
  database_url:
    file: ./secrets/database_url
  secret_key:
    file: ./secrets/secret_key
  postgres_password:
    file: ./secrets/postgres_password

volumes:
  media_volume:
  static_volume:
  postgres_volume:
