version: "3.8"

x-postgres-variables: &postgres-variables
  POSTGRES_DB: booker
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

services:
  app:
    command: gunicorn booker.wsgi:application --bind 0.0.0.0:8000
    environment:
      <<: *postgres-variables
      ALLOWED_HOSTS: ${APP_ALLOWED_HOSTS}
      SECRET_KEY: ${APP_SECRET_KEY}
    ports:
      - "${APP_PORT}:8000"
    networks:
      - shared_services
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media

networks:
  shared_services:
    external: true

volumes:
  static_volume:
  media_volume:
