version: "3.8"

x-postgres-variables: &postgres-variables
  POSTGRES_DB: booker
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

services:
  app:
    command: gunicorn booker.wsgi:application --bind 0.0.0.0:8000
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ORIGIN_WHITELIST: ${CORS_ORIGIN_WHITELIST}
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      B_CODE_LENGTH: ${B_CODE_LENGTH}
      B_DAYS_BETWEEN: ${B_DAYS_BETWEEN}
      B_TOTAL_APARTMENTS: ${B_TOTAL_APARTMENTS}
    ports:
      - "${APP_SERVICE_PORT}:8000"
    networks:
      - shared_services
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media

networks:
  shared_services:
    external: true

volumes:
  static_volume:
  media_volume:
