version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

secrets:
  postgres_password:
    file: ./secrets/postgres_password

volumes:
  db_volume:
