version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "${POSTGRES_SERVICE_PORT:-5432}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
