docker/build:
	docker-compose -f docker-compose.yml build

docker/down:
	docker-compose -f docker-compose.yml down

docker/down/dev:
	docker-compose -f docker-compose.dev.yml down

docker/up:
	docker-compose -f docker-compose.yml up -d

docker/up/dev:
	docker-compose -f docker-compose.dev.yml up -d
