# Generated by Django 3.2.10 on 2022-02-06 15:45

from django.db import migrations


def create_booking_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.create(name="booking")


class Migration(migrations.Migration):

    dependencies = [
        ("operator_api", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_booking_group)]
