# Generated by Django 3.2.10 on 2022-02-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booker_api", "0003_auto_20220209_2141"),
        ("operator_api", "0002_auto_20220206_1545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="apartments",
            field=models.ManyToManyField(
                related_name="operators",
                to="booker_api.Apartment",
                verbose_name="apartments",
            ),
        ),
    ]
