version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: cimg/postgres:13.5
        environment:
          POSTGRES_DB: circle_test
          POSTGRES_USER: root
    steps:
      - checkout
      - run:
          name: "Install"
          command: poetry install
      - run:
          name: "Run pytest"
          command: "poetry run pytest"

workflows:
  heroku-deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          context: booker-api-dev
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
