# Generated by Django 3.2.9 on 2021-12-03 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "apartment",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "APARTMENT 1"), (2, "APARTMENT 2")]
                    ),
                ),
                ("identifier", models.CharField(max_length=9)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "11:00 - 11:50"),
                            (2, "12:00 - 12:50"),
                            (3, "13:00 - 13:50"),
                            (4, "14:00 - 14:50"),
                        ]
                    ),
                ),
                (
                    "stay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booker_api.stay",
                    ),
                ),
            ],
            options={
                "unique_together": {("day", "slot")},
            },
        ),
    ]
