# Generated by Django 3.2.10 on 2021-12-23 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("number", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (11, "11:00 - 11:50"),
                            (12, "12:00 - 12:50"),
                            (13, "13:00 - 13:50"),
                            (14, "14:00 - 14:50"),
                            (15, "15:00 - 15:50"),
                            (16, "16:00 - 16:50"),
                            (17, "17:00 - 17:50"),
                            (18, "18:00 - 18:50"),
                            (19, "19:00 - 19:50"),
                            (20, "20:00 - 20:50"),
                            (21, "21:00 - 21:50"),
                        ]
                    ),
                ),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booker_api.apartment",
                    ),
                ),
            ],
            options={
                "unique_together": {("day", "slot")},
            },
        ),
    ]
