# Generated by Django 3.2.10 on 2021-12-23 00:11

import secrets
import string

import environ
from django.db import migrations

env = environ.Env(B_TOTAL_APARTMENTS=(int, 10))
alphabet = string.digits


def make_apartments(apps, schema_editor):
    Apartment = apps.get_model("booker_api", "Apartment")
    if not Apartment.objects.exists():
        for i in range(env("B_TOTAL_APARTMENTS")):
            code = None
            while code is None or Apartment.objects.filter(code=code).exists():
                code = "".join(secrets.choice(alphabet) for _ in range(4))

            Apartment.objects.create(code=code, number=i + 1)


class Migration(migrations.Migration):

    dependencies = [
        ("booker_api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(make_apartments),
    ]
