# Generated by Django 3.2.10 on 2021-12-23 00:11

import environ
from django.db import migrations

from booker_api.utils import make_code

env = environ.Env(TOTAL_APARTMENTS=(int, 10))


def make_apartments(apps, schema_editor):
    Apartment = apps.get_model("booker_api", "Apartment")
    if not Apartment.objects.exists():
        for i in range(env("TOTAL_APARTMENTS")):
            Apartment.objects.create(code=make_code(), number=i + 1)


class Migration(migrations.Migration):

    dependencies = [
        ("booker_api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(make_apartments),
    ]
