# Generated by Django 3.2.9 on 2021-12-08 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booker_api", "0001_squashed_0002_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stay",
            unique_together={("apartment", "date_from", "date_to")},
        ),
    ]
