# Generated by Django 3.2.10 on 2022-02-09 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booker_api", "0002_auto_20211223_0011"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apartment",
            options={"verbose_name": "apartment", "verbose_name_plural": "apartments"},
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ("-day", "slot"),
                "verbose_name": "booking",
                "verbose_name_plural": "bookings",
            },
        ),
        migrations.AlterField(
            model_name="apartment",
            name="code",
            field=models.CharField(max_length=10, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="number",
            field=models.PositiveSmallIntegerField(verbose_name="number"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booker_api.apartment",
                verbose_name="apartment",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="day",
            field=models.DateField(verbose_name="day"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="slot",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (11, "11:00 - 11:50"),
                    (12, "12:00 - 12:50"),
                    (13, "13:00 - 13:50"),
                    (14, "14:00 - 14:50"),
                    (15, "15:00 - 15:50"),
                    (16, "16:00 - 16:50"),
                    (17, "17:00 - 17:50"),
                    (18, "18:00 - 18:50"),
                    (19, "19:00 - 19:50"),
                    (20, "20:00 - 20:50"),
                    (21, "21:00 - 21:50"),
                ],
                verbose_name="slot",
            ),
        ),
    ]
