# Generated by Django 3.2.9 on 2021-12-08 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booker_api", "0002_alter_stay_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="apartments",
            field=models.ManyToManyField(
                related_name="apartments", to="booker_api.Apartment"
            ),
        ),
        migrations.AlterField(
            model_name="stay",
            name="apartment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booker_api.apartment"
            ),
        ),
    ]
