# Generated by Django 3.2.9 on 2021-12-08 21:29

import environ
from django.db import migrations
from django.utils.translation import gettext_lazy as _

env = environ.Env(B_TOTAL_APARTMENTS=(int, 10))


def make_apartments(apps, schema_editor):
    Apartment = apps.get_model("booker_api", "Apartment")
    if not Apartment.objects.exists():
        for i in range(env("B_TOTAL_APARTMENTS")):
            Apartment.objects.create(label=_(f"APARTMENT {i + 1}"))


class Migration(migrations.Migration):

    dependencies = [
        ("booker_api", "0003_auto_20211208_2125"),
    ]

    operations = [
        migrations.RunPython(make_apartments),
    ]
