# Generated by Django 3.2.9 on 2021-12-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booker_api", "0004_auto_20211208_2129"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
