name: build
on: [push]

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2
      - name: Build
        run: poetry install --no-root
      - name: Lint
        run: |
          poetry run black . --check
          poetry run isort . --check
          poetry run flake8 .
      - name: Test
        run: poetry run pytest
        env:
          SECRET_KEY: github-actions-secret-key
